
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lltxsklicotnhytxpwkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsdHhza2xpY290bmh5dHhwd2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjYyODEsImV4cCI6MjA1ODUwMjI4MX0.M0sl5qEeQEfQoN0-0g5Q7YmWdNC6i5AGWDue6RgxOy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
